# Generated by Django 5.1.1 on 2024-10-24 10:11

import django_admin_geomap
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0003_products_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
