# Generated by Django 5.1.1 on 2024-10-25 01:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0005_remove_products_address_products_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Имя'),
        ),
    ]
