# Generated by Django 5.1.1 on 2024-10-25 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0009_products_executor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_employees',
            field=models.IntegerField(default=0, max_length=2, verbose_name='Количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='products',
            name='executor',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
