# Generated by Django 5.1.1 on 2024-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0002_review_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
