# Generated by Django 5.1.1 on 2024-10-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0004_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='address',
        ),
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, related_name='Заказы', to='leathers.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
