# Generated by Django 5.1.1 on 2024-10-25 01:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0006_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
