# Generated by Django 5.1.1 on 2024-10-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leathers', '0007_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
